### ISSUE TITLE
패키지 구조 기반 생성

### ISSUE THREAD

**Issue by KHBM** [TeamCrazyPerformance/iamlazy-server#14]
패키지 구조는 
사용자, 통계, 회고, 할일, 설정이 구분되게 구성해 주셨으면 합니다.
각각의 하위에 controller, service 와 같은 구분이 따로 존재하도록 하며 
외부 서비스와 통신을 하기 위한 용도의 클래스는 infrastructure라는 패키지를 두어 집약시키면 좋겠습니다.

**Comment by jae-ran** [comment]
infrastructure 패키지를  아직 두지 못했습니다.
외부 서비스와 통신을 하기 위한 용도의 클래스라는 것이 어떤걸 말하는 건가요??

**Comment by KHBM** [comment]
현재는 저희가 외부 서비스랑 통신을 하지 않아서 생성을 안해도 될 거예요.
읏 제가 설명이 부족했네요.

가령 Redis라거나 kafka 또는 Zookeeper 등 외부와 통신을 위한 기능을 응집한 클래스를 만들 경우 그 클래스들이 들어갈 패키지입니다.

지금 시점에서는 매우 잘해주셨어요.

**Comment by KHBM** [comment]
@jae-ran  Done으로 두셨으나 질문이 남아 있어서 이 이슈는 닫지 않을게요!
이슈 해결되면 닫아 주세요. :D

**Comment by KHBM** [comment]
이슈 없는 것 같으므로 제가 닫겠습니다.
