### ISSUE TITLE
Server Git branching 전략 모델 기준안 세우기

### ISSUE THREAD

**Issue by KHBM** [TeamCrazyPerformance/iamlazy-server#18]
4주간의 프로젝트에 적용할 브랜치 전략을 세워봅니다.

**Comment by KHBM** [comment]
Git flow 를 사용하는 것은 기본적인

master, develop, feature, release, hotfix 등의 작업 브랜치와 tag 작업을 손쉽게 도와주는 것을 뜻합니다.

저희는 가능하면 cherry-pick 의 기능을 유용하게 사용할 수 있었으면 합니다.

다만, 이것에 익숙하지 않을 경우가 있습니다.

이에 고뇌중입니다.

**Comment by KHBM** [comment]
master - 저희의 기본 production 단계로 바로 배포 가능한 커밋만을 담는 브랜치 입니다. Tag를 같이 생성해 주세요.    
work - 저희의 기능 추적 브랜치로 합니다.  master 와 동일하나 production이 롤백된 경우 차이가 있게 됩니다. HEAD가 됩니다.   
feature - 기능 개발 단위는 work 기준 브랜치에서 분기하여 시작합니다.   병합 시 -i 옵션을 주는 건 어떨까요.. 음..

**Comment by genie-youn** [comment]
feature는 work 에서 나와서 기능 구현 후에 work 로 PR 올리고 머지되게 될까요?ㅎㅎ 용처를 보면 일반적인 develop과 비슷한 롤인것 같은데, work라는 이름을 부여한 특별한 이유가 있을까요~? 단순한 호기심입니다 ㅎㅎ

**Comment by KHBM** [comment]
피드백 감사드립니다!

develop 아직 고민중이긴 하나 대략적으로는 아래와 같이 하고자 합니다.

 개발자로 하여금 머지와 병합을 자유로이 합니다. 기능에 필요한 커밋 단위를 체리 픽 해서 섞어 보기도 하고 떼 보기도 하며, 리버트도 수행하고 하는 일종의 제약없는(free) 브랜치로서 그 의의를 둬볼까 했어요. 각자 환경에서 develop 브랜치를 두면 각자가 자신의 실험대(ex: testbed) 같은 브랜치를 각자 갖는거죠. 따라서 remote에는 명시하지 않았습니다.

다만 통상의 develop과 같은 master 흐름을 따라가며 개발 분기를 수행하기 위한 브랜치는 필요했기에 work라는 '작업 거점'의 구분을 두고자 했습니다.

 DEV(개발) 환경에 대해 훅을 걸 때는 develop을 대상으로 두게 되긴 하는데 이 방식이 보통은 이름 매치 방식으로 따라가기에, 이 때다 싶을 때 develop 이란 브랜치를 work의 특정 브랜치에서 checkout 하면 걸리더라고요. 

아직 부족하기에 많은 의견 주시면 감사하겠습니다.

@jae-ran @joi0104 분들께서도 의견 풍부하게 주시면 변경 가능합니다. 90%만 확정이 되었어요 :D

**Comment by KHBM** [comment]
하다가 불편사안 있으면 말하며 해결하는 것으로 합니다.
